### ISSUE TITLE
Issue with query string parsing in 10.11.2

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-node#256]
### Software versions

_Please provide at least OS and version of pact-js_

- **OS**: tested on Linux and Mac
- **Pact Node version**: 10.11.2
- **Node Version**: 12.18.0

FYI just found an issue relating to query string parsing in this version of the standalone. I need to get to the bottom of why, but an example in the JS repo just started failing after upgrade:

Request:

```js
    const catsListRequest = {
      uponReceiving: "a request for cats with given catId",
      withRequest: {
        method: "GET",
        path: "/cats",
        query: {
          "catId[]": Matchers.eachLike("1"),
        },
        headers: {
          Accept: "application/json",
        },
      },
    }
```

Client code:

```js
exports.getMeCats = endpoint => {
  const url = endpoint.url

  return axios
    .request({
      method: "GET",
      baseURL: url,
      url: "/cats?catId[]=2&catId[]=3",
      headers: { Accept: "application/json" },
    })
    .then(response => response.data)
}
```

Log file:

```
E, [2021-01-27T22:38:04.829205 #15023] ERROR -- : No matching interaction found for GET /cats?catId[]=2&catId[]=3
E, [2021-01-27T22:38:04.829228 #15023] ERROR -- : Interaction diffs for that route:
E, [2021-01-27T22:38:04.829675 #15023] ERROR -- : Diff with interaction: "a request for cats with given catId" given "i have a list of cats"
Diff
--------------------------------------
Key: - is expected
     + is actual
Matching keys and values are not shown
 {
   "query": {
-    "catId[]": [
-      "1",
+    "catId": [
+      "2",
+      "3"
     ]
   }
 }
Description of differences
--------------------------------------
* Could not find key "catId[]" (keys present are: catId) at $.query
* Did not expect the key "catId" to exist at $.query
W, [2021-01-27T22:38:04.836258 #15023]  WARN -- : Verifying - actual interactions do not match expected interactions.
Incorrect requests:
	GET /cats?catId[]=2&catId[]=3 (request query did not match)
W, [2021-01-27T22:38:04.836304 #15023]  WARN -- : Incorrect requests:
	GET /cats?catId[]=2&catId[]=3 (request query did not match)
```

I'll dig into more later, but this was the quickest spot to re-raise the issue

## See also

#255

**Comment by TimothyJones** [comment]
Hmm. I remember @bethesque saying there was some problem with query string parsing in an earlier version, but I thought it was fixed. Beth, do you happen to recognise this, or shall we dig further on the JS side?

**Comment by mefellows** [comment]
Yeah, it's dealt with differently in the v3 code. But I think this is a breaking backwards incompatible change, so for now I've deprecated that latest version that went out because it got caught by a feature spec in Pact JS. 

We can debate the merits of all of that tomorrow, and re-release if we're happy.

**Comment by TimothyJones** [comment]
I think that’s the right call, thanks.

My local Windows tests didn’t pass either, due to a different problem (possibly Windows long path, hard to tell). A tomorrow problem, too.

**Comment by bethesque** [comment]
I hate query strings so much 😢 I'll have a look at it.

**Comment by mefellows** [comment]
Did that latest release #257 contain the fix for query strings? I pulled it in and ran the tests, but it still fails for me. Need me to setup an example in the e2e repo?

**Comment by bethesque** [comment]
No. It was an unrelated update to pact-support.

**Comment by mefellows** [comment]
ah cool 👍

**Comment by bethesque** [comment]
Fixed in https://github.com/pact-foundation/pact-support/commit/a86a3e307ef5b6ae77cb06efc2647e61e628687b

Probably. It's all a bit dogy. That code definitely allows some false positives around the query matching.

**Comment by bethesque** [comment]
And BAM https://github.com/pact-foundation/pact-node/pull/258 Like a little Rube Goldberg machine.

**Comment by TimothyJones** [comment]
Fixed in v10.11.4
